### ISSUE TITLE
Compat feature test fails

### ISSUE THREAD

**Issue by dariusc93** [ipfs-rust/libp2p-bitswap#37]
Compat feature fails test with 

```
thread 'behaviour::tests::compat_test' panicked at 'Some(Complete(QueryId(0), Err(Failed to retrieve block QmXQsqVRpp2W7fbYZHi4aB2Xkqfd3DpwWskZoLVEYigMKC.))) is not a complete event', src/behaviour.rs:840:13
```

**Comment by rkuhn** [comment]
Yes, it tries to connect to some IP address and fetch some data, but that IP address doesn’t answer on port 4001. Should we switch to some well-known Cid that is served by some well-known IPFS gateway?

**Comment by rkuhn** [comment]
I’ve done this in 84490251c70b825d50c9da75edb7e521cef29845: using the first entry in the go-ipfs bootstrap node list installed by default, and a Cid corresponding to the Apache 2 LICENSE file.

Thanks for noticing!
