### ISSUE TITLE
Panic in Bitswap::ledger() unwrap

### ISSUE THREAD

**Issue by scanlime** [ipfs-rust/libp2p-bitswap#6]
I just saw this unwrap() panic:

```
     61     fn ledger(&mut self, peer_id: &PeerId) -> &mut Ledger<MH> {
     62         self.connected_peers.get_mut(peer_id).unwrap()
     63     }
```

Not exactly sure what happened yet but peers may be disconnecting unexpectedly because I'm hitting the file descriptor limit. In any case, this unwrap seems like a problem.

**Comment by dvc94ch** [comment]
If you can come up with a solution, I'm happy to merge it
